server:
  address: localhost
  port: 8220

jwt:
  secret-key: iDBM3ECuOXB08NuGQ8wM4XFwjSfSSMhYG5me9+wVqeA=

spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:websiteDB;DB_CLOSE_DELAY=-1;
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: websitemaster591@gmail.com
    password: ptzkgnkojglqzmgj
    properties:
      smtp:
        socketFactory:
          port: 465
          class: javax.net.ssl.SSLSocketFactory
        auth: true
        starttls:
          enable: true


mail:
  store:
    protocol: imap
  imap:
    host: imap.gmail.com
    port: 993

contacts: src/main/resources/Contacts.json
paypal:
  client-id: AbyhDjGHwvmxhdU6sKk_6ysArSAqEhKLBmw3-dnL30erGpc8ngu5rFCmde7azh1GWzQJyMHDATOkY6fz
  client-secret: ELBINSy2I2H88DDMel68VKp1dsMNVJEYtl-gLSMRgIS8OC5snnrNIgb_hcg3jofjwJfPYXipB--bEN9N
  mode: sandbox





